spring.application.name=task-service

spring.datasource.url=jdbc:postgresql://localhost:5432/TaskManagement
spring.datasource.username=postgres
spring.datasource.password=lol
spring.datasource.driver-class-name=org.postgresql.Driver
server.port=8081


spring.jpa.hibernate.ddl-auto=update